"use client";

import { ChakraProvider } from "@chakra-ui/react";
import "./globals.css";
import React from "react";
import { theme } from "./chakra/theme";
import Navbar from "./components/Navbar/Navbar";
import "@fontsource/open-sans/300.css";
import "@fontsource/open-sans/400.css";
import "@fontsource/open-sans/700.css";
import { RecoilRoot } from "recoil";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <RecoilRoot>
          <ChakraProvider theme={theme}>
            <Navbar />
            {children}
          </ChakraProvider>
        </RecoilRoot>
      </body>
    </html>
  );
}
